changed the require directory again due to..
Error: Failed to apply catalog: Could not find dependency File[/etc/condor/config.d/] for File[/etc/condor/config.d/cluster.conf] at /etc/puppet/environments/production/modules/profile/manifests/osg/cefiles/configure.pp:69